name: TikTok Fans Tracker & Deploy to GH Pages

on:
  schedule:
    # 每小时执行一次（UTC时间）
    - cron: '0 * * * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  track-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium pandas matplotlib
          # 安装Chrome浏览器
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          # 安装ChromeDriver
          CHROME_VERSION=$(chromium-browser --version | grep -oP '\d+\.\d+\.\d+\.\d+')
          wget https://chromedriver.storage.googleapis.com/$CHROME_VERSION/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
      
      - name: Run tracker script
        run: python tiktok_fans_tracker.py
      
      - name: Create index.html for GH Pages
        run: |
          echo "<!DOCTYPE html>" > index.html
          echo "<html lang='zh-CN'>" >> index.html
          echo "<head>" >> index.html
          echo "  <meta charset='UTF-8'>" >> index.html
          echo "  <meta name='viewport' content='width=device-width, initial-scale=1.0'>" >> index.html
          echo "  <title>抖音主播粉丝跟踪</title>" >> index.html
          echo "  <style>" >> index.html
          echo "    body { font-family: Arial, sans-serif; max-width: 1200px; margin: 0 auto; padding: 20px; }" >> index.html
          echo "    h1 { color: #333; text-align: center; }" >> index.html
          echo "    .chart-container { text-align: center; margin: 30px 0; }" >> index.html
          echo "    .chart-container img { max-width: 100%; border: 1px solid #ddd; border-radius: 4px; padding: 5px; }" >> index.html
          echo "    .data-table { width: 100%; border-collapse: collapse; margin: 20px 0; }" >> index.html
          echo "    .data-table th, .data-table td { border: 1px solid #ddd; padding: 8px; text-align: left; }" >> index.html
          echo "    .data-table th { background-color: #f2f2f2; }" >> index.html
          echo "    .last-update { color: #666; text-align: center; margin-top: 20px; }" >> index.html
          echo "  </style>" >> index.html
          echo "</head>" >> index.html
          echo "<body>" >> index.html
          echo "  <h1>抖音主播粉丝数变化趋势</h1>" >> index.html
          echo "  <div class='chart-container'>" >> index.html
          echo "    <img src='fans_trend.png' alt='粉丝变化趋势图'>" >> index.html
          echo "  </div>" >> index.html
          echo "  <h2>最新数据</h2>" >> index.html
          echo "  <table class='data-table'>" >> index.html
          echo "    <tr><th>时间</th><th>粉丝数量</th></tr>" >> index.html
          # 添加最新的10条数据
          echo "$(tail -n 11 fans_data.csv | sed '1d' | awk -F ',' '{printf "    <tr><td>%s</td><td>%s</td></tr>\n", $1, $2}')" >> index.html
          echo "  </table>" >> index.html
          echo "  <p class='last-update'>最后更新: $(date +'%Y-%m-%d %H:%M:%S') UTC</p>" >> index.html
          echo "</body>" >> index.html
          echo "</html>" >> index.html
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages  # 部署到gh-pages分支
